language: python
python:
  - 3.7
  - 3.9
  - pypy
  - pypy3
env:
  - DJANGO=3.1.7
before_install:
  - export DJANGO_SETTINGS_MODULE=suit.tests.settings
install:
  - pip install -q Django==$DJANGO
  - pip install .
script:
  - python manage.py test suit
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 2.7
      env: DJANGO=2.0.2
    - python: pypy
      env: DJANGO=2.0.2
